#!/bin/bash

if [ -f ./setup ]
then
  source ./setup
fi

if [ -f ./custom ]
then
  source ./custom
fi

if [ -d ./custom.d ]
then
  for FILE in $(find ./custom.d -type f -iname \*.sh | sort)
  do
    source ${FILE}
  done
fi

export ROOT_URL="${ROCKETCHAT_ROOT_URL}"
export PORT=3000
export Accounts_AvatarStorePath="${ROCKETCHAT_AVATARS_PATH}"

if [[ -n "${ROCKETCHAT_MONGO_USERNAME}" || -n "${ROCKETCHAT_MONGO_PASSWORD}" ]]
then
  export MONGO_URL="mongodb://${ROCKETCHAT_MONGO_USERNAME}:${ROCKETCHAT_MONGO_PASSWORD}@${ROCKETCHAT_MONGO_HOST}:${ROCKETCHAT_MONGO_PORT}/${ROCKETCHAT_MONGO_DATABASE}"

  if [[ -n "${ROCKETCHAT_MONGO_AUTH_SOURCE}" ]]
  then
    export MONGO_UR="${MONGO_URL}?authSource=${ROCKETCHAT_MONGO_AUTH_SOURCE}"
  fi
else
  export MONGO_URL="mongodb://${ROCKETCHAT_MONGO_HOST}:${ROCKETCHAT_MONGO_PORT}/${ROCKETCHAT_MONGO_DATABASE}"
fi

if [[ -n "${ROCKETCHAT_MONGO_OPLOG_USERNAME}" || -n "${ROCKETCHAT_MONGO_OPLOG_PASSWORD}" ]]
then
  export MONGO_OPLOG_URL="mongodb://${ROCKETCHAT_MONGO_OPLOG_USERNAME}:${ROCKETCHAT_MONGO_OPLOG_PASSWORD}@${ROCKETCHAT_MONGO_HOST}:${ROCKETCHAT_MONGO_PORT}/${ROCKETCHAT_MONGO_REPL_DATABASE}?replSet=${ROCKETCHAT_MONGO_REPL_SET}"

  if [[ -n "${ROCKETCHAT_MONGO_OPLOG_AUTH_SOURCE}" ]]
  then
    export MONGO_OPLOG_URL="${MONGO_OPLOG_URL}&authSource=${ROCKETCHAT_MONGO_OPLOG_AUTH_SOURCE}"
  fi
else
  export MONGO_OPLOG_URL="mongodb://${ROCKETCHAT_MONGO_HOST}:${ROCKETCHAT_MONGO_PORT}/${ROCKETCHAT_MONGO_REPL_DATABASE}?replSet=${ROCKETCHAT_MONGO_REPL_SET}"
fi

echo "> starting rocketchat service"
exec su-exec rocketchat node /srv/www/bundle/main.js
