#!/bin/bash
set -eo pipefail

if [ -f ./setup ]
then
  source ./setup
fi

export ROOT_URL="${ROCKETCHAT_ROOT_URL}"
export PORT=3000
export Accounts_AvatarStorePath=/var/lib/rocketchat/avatars

if [[ -n "${ROCKETCHAT_MONGO_USERNAME}" || -n "${ROCKETCHAT_MONGO_PASSWORD}" ]]
then
  export MONGO_URL="mongodb://${ROCKETCHAT_MONGO_USERNAME}:${ROCKETCHAT_MONGO_PASSWORD}@${ROCKETCHAT_MONGO_HOST}:${ROCKETCHAT_MONGO_PORT}/${ROCKETCHAT_MONGO_DATABASE}"
else
  export MONGO_URL="mongodb://${ROCKETCHAT_MONGO_HOST}:${ROCKETCHAT_MONGO_PORT}/${ROCKETCHAT_MONGO_DATABASE}"
fi

exec su-exec rocketchat node /srv/www/bundle/main.js
