#!/bin/bash
set -eo pipefail

if [[ ! -d /var/lib/rocketchat/avatars ]]
then
  mkdir -p \
    /var/lib/rocketchat/avatars
fi

chown -R rocketchat:rocketchat \
  /var/lib/rocketchat

wait-for-it \
  -t ${ROCKETCHAT_MONGO_TIMEOUT} \
  ${ROCKETCHAT_MONGO_HOST}:${ROCKETCHAT_MONGO_PORT}

if [[ $? -ne 0 && "${ROCKETCHAT_MONGO_TEST_FAIL}" == "true" ]]
then
  echo "Database didn't came up in time!"
  /bin/s6-svscanctl -t /etc/s6
  exit 1
fi
